# Generated by Django 5.0.7 on 2025-12-31 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_2fA_enabled',
            new_name='is_2fa_enabled',
        ),
    ]
